### ISSUE TITLE
stopped working does not work

### ISSUE THREAD

**Issue by Avannit** [zimonitrome/vscode-color-blocks#6]
Hi, I don't know what happened, but versions 2.0.0 and 2.1.0 do not work, put it on 1.0.6 and everything worked

I have the usual code of the latest version, not an insider

**Comment by zimonitrome** [comment]
Okay I will look into this. Thanks for reporting!

On the top of my head it could be the new setting to toggle color blocks on/off that has a bad default vaule.

I also found that the latest release is a little laggy (as in it slows down the editor) so there are a few hotfixes that needs to be done ASAP.

**Comment by zimonitrome** [comment]
On a second note, could you provide some example of code that does not work?

I have not been able to reproduce the bug yet.

**Comment by Avannit** [comment]
@zimonitrome

And so, after your post, I realized that perhaps the problem lies elsewhere

I went through all my plugins that do my code coloring and found that after turning on [todo-tree](https://github.com/Gruntfuggly/todo-tree) plugin [vscode-color-blocks](https://github.com/zimonitrome/vscode-color-blocks) loses functionality

Сan you confirm my version?

**Comment by zimonitrome** [comment]
@Avannit Yes I tried downloading this extension too and I have the same problem...

I will try to look into the code of todo-tree and see if I can find anything that is incompatible.

**Comment by Avannit** [comment]
@zimonitrome Can you make the coloring from version 1.0.6 and the functionality from version 2.1.0?

**Comment by zimonitrome** [comment]
I will look into it. Otherwise I will try to bisect or rollback some commits in the next few days to find when this issue becamr a problem.

**Comment by zimonitrome** [comment]
It is pretty odd... 
I am using some new features from ES2022, more specifically [RegExp match indices](https://inspiredwebdev.com/everything-new-in-es2022/#regexp-match-indices) using the flag `d`. This works fine when TODO tree is not installed but otherwise vscode complains:

```
stack trace: SyntaxError: Invalid flags: d
	at _ (...\.vscode\extensions\gruntfuggly.todo-tree-0.0.215\dist\extension.js:114:74341)
	at Array.<anonymous> (...\.vscode\extensions\gruntfuggly.todo-tree-0.0.215\dist\extension.js:114:3580)
	at Object.parse (...\.vscode\extensions\gruntfuggly.todo-tree-0.0.215\dist\extension.js:114:71938)
	at Object.parse (...\.vscode\extensions\gruntfuggly.todo-tree-0.0.215\dist\extension.js:1:12529)
	at Object.parse (...\.vscode\extensions\gruntfuggly.todo-tree-0.0.215\dist\extension.js:114:415)
	at i (...\.vscode\extensions\gruntfuggly.todo-tree-0.0.215\dist\extension.js:52:165)
	at Array.get [as indices] (...\.vscode\extensions\gruntfuggly.todo-tree-0.0.215\dist\extension.js:52:2895)
	at DecorationRangeHandler.addNewDecorationRanges (...\vscode-color-blocks\dist\extension.js:1735:95)
```

I think I will need to learn some more about TS/JS target versions to realize how this error occurs. Ideally I would want to keep the current behavior because it is very convenient, but I will also look into what a refactor would entail.

**Comment by zimonitrome** [comment]
The error seems to be that Todo Tree uses [a polyfill for RegExp Match Indices](https://github.com/rbuckton/regexp-match-indices) and this polyfill has an error that is only present when it is "compiled" to javascript ([see issue](https://github.com/rbuckton/regexp-match-indices/issues/15)).

It is odd as why this error is not triggered until vscode-color-blocks is loaded. Perhaps because Todo Tree never uses the `d` flag explicitly? I am not sure if I want to implement RegExp Match Indices in the same way that Todo Tree does since that may cause the same error to another plugin.

**Comment by zimonitrome** [comment]
"Downgraded" to a more naive regex without the `d` flag in https://github.com/zimonitrome/vscode-color-blocks/commit/2b3b8463a84c270125195a533a02fb1c69a1261a

The original TODO-tree plugin seems to be a bit abandoned but other extensions that implement its own polyfill for this (like "better TODO tree") should still work now.
